---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by felix.
--- DateTime: 23/04/2020 00:35
---

local targets = require("luabuild.targets");
local ninja = require("luabuild.ninja");

local font_packer = targets.executable {
    name = "font_packer";
    sources = {
        "main.cpp"
    };
    libs = {
        public = {
            lyra_lib, stb_lib, yaml_lib
        }
    };
    include_directories = {
        public = { "../../"};
    }
}

ninja.writeRule({
   name = "FONT_PACK";
   command = font_packer.exe.." -o $name $in";
});

function font_pack(name, input)
    ninja.writeStep({
        rule = "FONT_PACK";
        outputs = CURRENT_DIRECTORY..name..".bin".." "..CURRENT_DIRECTORY..name..".png";
        inputs = "../"..CURRENT_DIRECTORY..input;
        implicit_dependencies = { font_packer.exe };
        variables = {
            name = CURRENT_DIRECTORY..name;
        }
    });
end