---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by felix.
--- DateTime: 23/04/2020 00:00
---


local targets = require("luabuild.targets");
local ninja = require("luabuild.ninja");

local shaderPacker = targets.executable {
    name = "shader_packer";
    sources = {
        "shader_packer.cpp"
    };
    libs = {
        public = {
            yaml_lib, lyra_lib
        };
    };
    include_directories = {
        public = {
            "../../"
        }
    }
}

ninja.writeRule({
    name = "SHADER_PACK";
    command = shaderPacker.exe.." -o $out $in";
});

function shader_pack(input)
    ninja.writeStep({
        rule = "SHADER_PACK";
        outputs = CURRENT_DIRECTORY..input..".bin";
        inputs = "../"..CURRENT_DIRECTORY..input;
        implicit_dependencies = { shaderPacker.exe };
    });
end