---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by felix.
--- DateTime: 23/04/2020 00:00
---


local targets = require("luabuild.targets");
local ninja = require("luabuild.ninja");

local script_path = "../"..CURRENT_DIRECTORY.."shader_packer.lua";

ninja.writeRule({
    name = "SHADER_PACK";
    command = "lua "..script_path.." $vertex $fragment $out";
})

function shader_pack(name, vertex, fragment)
    ninja.writeStep({
        rule = "SHADER_PACK";
        outputs = CURRENT_DIRECTORY..name;
        inputs = "../"..CURRENT_DIRECTORY..vertex.." ".."../"..CURRENT_DIRECTORY..fragment;
        variables = {
            vertex = "../"..CURRENT_DIRECTORY..vertex;
            fragment = "../"..CURRENT_DIRECTORY..fragment;
        };
        implicit_dependencies = {
            script_path
        }
    })
end